### ISSUE TITLE
Code typo in README.md

### ISSUE THREAD

**Issue by anasaijaz** [RocketChat/developer-docs#122]
# Prerequisites

Please answer the following questions before opening an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] This issue concerns the developer's docs

### Current Behavior

The Contribute section seems to have a code typo 

`{% content-ref url="rocket.chat/contribute-to-rocket.chat/" %} [contribute-to-rocket.chat](https://github.com/RocketChat/developer-docs/blob/master/rocket.chat/contribute-to-rocket.chat) {% endcontent-ref %}`

What is the intended line here? 
So I can fix this issue 
Thank you

Image 
![image](https://user-images.githubusercontent.com/27632474/177010812-2ae92e99-5d4a-4d93-b5e6-573bf949097a.png)

**Comment by Faria-TechWrite** [comment]
It is not really an issue. We use gitbook for our docs and this is how gitbook links are being converted into markdown. Please view the document here. https://developer.rocket.chat/
