### ISSUE TITLE
Example with "blocks" in chat.sendMessage API

### ISSUE THREAD

**Issue by yoyojin-dev** [RocketChat/developer-docs#130]
### Expected Behavior
In docs https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/chat-endpoints/sendmessage possibility to use UIKit "blocks" in message body is not described, but it works. There is even no mention about "blocks". Could you please add this example to the API description?

## Extras

And as it works, I have a question - how can I send DM by chat.sendMessage API with blocks section?
I know I can use chat.postMessage but "blocks" doesn't work there, so I wonder if I'm able to use chat.sendMessage or is it possible to send "blocks" through chat.postMessage.

**Comment by Rodriq** [comment]
Please do you mind sharing a sample of such a request?

**Comment by Faria-TechWrite** [comment]
https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/chat-endpoints/sendmessage
