### ISSUE TITLE
Hubot has been inactive for two years, and is still in the doc

### ISSUE THREAD

**Issue by matthias4217** [RocketChat/developer-docs#131]
# Prerequisites

Please answer the following questions before opening an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] This issue concerns the developer's docs

> This template can be used to report
>
> - [Existing Docs issues](#existing-docs)
>
> - [New Docs request](#new-docs-request)
>
> **Clear out any irrelevant section**

## Existing Docs

The documentation for bot development doesn't seem up to date. [Hubot's repository](https://github.com/RocketChat/hubot-rocketchat) has been inactive for two years, and is still the first link in the list on the [Creating your own bot page](https://developer.rocket.chat/bots/creating-your-own-bot-from-scratch#2.-code-your-bot).

**Comment by Faria1212** [comment]
Corrected. We appreciate your input.
