### ISSUE TITLE
Duplicated instruction for Linux environment setup

### ISSUE THREAD

**Issue by amottier** [RocketChat/developer-docs#133]
# Prerequisites

- [x] I checked to make sure that this issue has not already been filed
- [x] This issue concerns the developer's docs

### Expected Behavior

A single source of truth should exists regarding how to setup a Linux development environment. It should include information such as the recommendation to use n node package manager or nvm to avoid issue related to Node version.

### Current Behavior

Documentation available at https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/linux is generated from https://github.com/RocketChat/developer-docs/blob/master/rocket.chat/rocket-chat-environment-setup/linux.md.

Another similar documentation exist in https://github.com/RocketChat/developer-docs/blob/master/rocket.chat/rocket.chat-server/linux.md

The second one (`rocket.chat-server/linux.md`) seems the one to be kept because it suggests the usage of node package manager or nvm.

The first documentation page, the one currently in use (`rocket-chat-environment-setup/linux.md`) has been created recently (Aug 22) by @Rodriq whereas the second one as been created back in 2021 and has several contributors (@yashovardhan, @debdutdeb, @JaroJu, @Dnouv, @Faria-TechWrite and even @Rodriq).

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Compare https://github.com/RocketChat/developer-docs/blob/master/rocket.chat/rocket-chat-environment-setup/linux.md and https://github.com/RocketChat/developer-docs/blob/master/rocket.chat/rocket.chat-server/linux.md
2. Checkout what is available at https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/linux

**Comment by Rodriq** [comment]
Thank you for pointing this out @amottier 
This is probably a result of a sync issue we were facing for a while with Gitbook. You are right the second case has a history of contributions and I remember updating it for `Rocket.Chat v5.x` as seen in the screenshot down there.

The current docs being served were Authored by one of the PRs I made in an attempt to synchronize the directories of files and permalinks on Gitbook.

This will be sorted out. Thank you again :)

**Comment by amottier** [comment]
Thanks a lot for the quick feedback @Rodriq
Don't hesitate to let me know if I can be of any help for testing of anything else.

**Comment by Rodriq** [comment]
@amottier Docs updated. That is what the docs was supposed to look like.
I wonder which other content we might be missing because of this sync issue. 😮‍💨
