### ISSUE TITLE
Invalid body format in invite team member

### ISSUE THREAD

**Issue by Alenjojo** [RocketChat/developer-docs#134]
# Prerequisites

Please answer the following questions before opening an issue.

- [ ✅] I checked to make sure that this issue has not already been filed
- [✅ ] This issue concerns the developer's docs

> This template can be used to report
>
> - [Existing Docs issues](#existing-docs)
>
> - [New Docs request](#new-docs-request)
>
> **Clear out any irrelevant section**

### Expected Behavior

The Example call given the userId and roles should be having double inverted commas
### Current Behavior

What is the current behavior?

The Example call given the userId and roles is missing double inverted commas under the members, so now when we copy the curl and use it its would be in a bad format and Bad request occurs

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 - Goto - https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/teams-endpoints/add-members
2. step 2 - in the Example Call we can see the the userId and roles argument without double inverted commas

### Details

Even thou after fixing it was getting method not allowed. Not sure whats wrong

## Extras

Please include any relevant information or images

**Comment by Faria-TechWrite** [comment]
The example call given was rectified. The call was made successfully. Please double-check your permissions.

**Comment by Alenjojo** [comment]
well, yea now its has been rectified after this issue been raised. But there's one more bug left.
The same API to add members doesn't work at all. I tried all the way possible it say's Method not allowed. Even if i remove the header value it doesn't say unauthorized.
