### ISSUE TITLE
Endpoint 'sendMessage' was removed with no proper message

### ISSUE THREAD

**Issue by yoyojin-dev** [RocketChat/developer-docs#135]
Hello, @Faria-TechWrite !
1 month ago we discussed the changes to the doc in `chat.sendMessage` endpoint here: https://github.com/RocketChat/developer-docs/issues/130.
Now, as I can see, the information about this endpoint was removed from the developers documentation at all with no proper comments: https://github.com/RocketChat/developer-docs/commit/76c9a665fb53b470d10d3224fab8eb37d3c4c755.
This endpoint is vital to us, so could you please provide some details why it happened and if the endpoint is not going to be supported anymore?

**Comment by Faria-TechWrite** [comment]
Hey, @yoyojin-dev Thank you for reaching out to us. This endpoint doc was taken down temporarily. We are using it for a hiring challenge. It will be back up as soon as we close the position. If it is urgent, share your email address and I'll send the doc to you.

**Comment by yoyojin-dev** [comment]
Thank you a lot for the rapid reponse!
No need to share, we know how to use it. Just were afraid of disabling this API in future releases :)

**Comment by nugmanoff** [comment]
Hey @Faria-TechWrite! I ended up here by trying to wrap my head around why doc is gone and its history is also gone ;) 
I am right now working on integrating Rocket Chat into my app, so I would love to receive the copy of the doc. My email is a.nugmanoff@gmail.com

**Comment by nugmanoff** [comment]
@Faria-TechWrite thanks for that one! that really saved my day!

**Comment by Faria-TechWrite** [comment]
Doc is back up! :)
