### ISSUE TITLE
Add information manage node version in WSL setup

### ISSUE THREAD

**Issue by EduardoGurgel** [RocketChat/developer-docs#141]
# Prerequisites
- [x] I checked to make sure that this issue has not already been filed
- [x] This issue concerns the developer's docs

### Expected Behavior

Yarn build and yarn dev should end up starting a server

### Current Behavior

The current Node version v19.3.0 does not satisfy the required version 14.19.3.

![image](https://user-images.githubusercontent.com/51385738/207617236-e5c85e6d-9ba6-42d3-8ece-652f2dc2785f.png)

### Details

14.19.3 sucessfully runs the server

![image](https://user-images.githubusercontent.com/51385738/207618659-b9d05788-4324-493c-8da3-c04c5af1c8eb.png)

Please provide your details and description here.
> Add any information if you have to help develop the docs

## Extras
 Add information manage node version in WSL setup

* To easily manage the node versions on your machine, install the [n node package manager](https://www.npmjs.com/package/n) or [nvm ](https://github.com/nvm-sh/nvm)then install and switch to the desired node version to use. Example:

```bash
npm install -g n
n 14.19.3
node -v
```

**Comment by art1505** [comment]
Tested! It was of great help to complete the build on my machine on windows 10.👍👍👍
