### ISSUE TITLE
Devloping on macOS

### ISSUE THREAD

**Issue by git-anurag-hub** [RocketChat/developer-docs#15]
We must add the guide about setting up the developer env. on the macOS machine. The docs now only deals with the developing on the linux and windows machine.

**Comment by Udit-takkar** [comment]
i am working on this. can you assign it to me? @git-anurag-hub

**Comment by git-anurag-hub** [comment]
Sure @Udit-takkar, this is free country. :)

**Comment by Rodriq** [comment]
Docs updated https://developer.rocket.chat/rocket.chat/rocket.chat-server/mac-osx
