### ISSUE TITLE
rooms.saveRoomSettings API docs incorrectly specify the name of the endpoint and the HTTP method, lack examples

### ISSUE THREAD

**Issue by joshburnett** [RocketChat/developer-docs#151]
# Prerequisites

Please answer the following questions before opening an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] This issue concerns the developer's docs

## Existing Docs
For the [rooms.SaveRoomSettings API](https://github.com/RocketChat/developer-docs/blob/master/reference/api/rest-api/endpoints/core-endpoints/rooms-endpoints/save-room-settings.md) endpoint.

### Expected Behavior
Endpoint URL should be `/api/v1/rooms.saveRoomSettings` and the HTTP Method should be `POST`.

### Current Behavior
Endpoint URL is currently `/api/v1/rooms.get` and the HTTP Method should be `GET`.

### Details
It would also be nice to see some examples of what room details can be updated via this method, as not all can be (such as the `"broadcast"` property).

**Comment by joshburnett** [comment]
While the code examples properly list the HTTP method as `POST`, the table at the top of the page still lists it as `GET`:

![image](https://user-images.githubusercontent.com/12973799/220636178-1bfb9e0a-e392-4a8c-ab8b-3cad1cec5c92.png)

**Comment by Faria-TechWrite** [comment]
We fixed it. Thank you

**Comment by joshburnett** [comment]
What version of the file is fixed? I don't see it. I still see the `GET` HTTP method listed.

**Comment by Faria-TechWrite** [comment]
https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/rooms-endpoints/save-room-settings the changes get a while to get synced

**Comment by joshburnett** [comment]
👍🏻 Great, thank you so much!
