### ISSUE TITLE
Use of Flipper for debugging is not mentioned in "Mobile App Environment Setup"

### ISSUE THREAD

**Issue by floels** [RocketChat/developer-docs#163]
# Prerequisites

Please answer the following questions before opening an issue.

- [X] I checked to make sure that this issue has not already been filed
- [X] This issue concerns the developer's docs

# New Docs Request

I recently went through the [Mobile App Environment Setup section of the developer's docs](https://developer.rocket.chat/mobile-app/mobile-app-environment-setup) to set up my local environment and contribute to the `RocketChat/Rocket.Chat.ReactNative` project.

The instructions are clear enough, except they don't mention explicitly that [Flipper](https://fbflipper.com/) can be used for debugging. This is not mentioned in the [React Native doc linked](https://reactnative.dev/docs/environment-setup) either.

Maybe it's just for me but Flipper was actually the only debugger that worked (Chrome couldn't retrieve the source maps for some reason). I would have found it useful if the docs mentioned it, at least as a possible option.

Should we add a short sentence about it in the `Mobile App Environment Setup` section?

**Comment by diegolmello** [comment]
Hey. We don't have it documented because it's not enabled by default on iOS.
