### ISSUE TITLE
`yarn prettier` instead of `yarn prettier-lint` in "Testing your Mobile App" section

### ISSUE THREAD

**Issue by floels** [RocketChat/developer-docs#164]
# Prerequisites

Please answer the following questions before opening an issue.

- [X] I checked to make sure that this issue has not already been filed
- [X] This issue concerns the developer's docs

# Existing Docs

The [Testing your Mobile App section](https://developer.rocket.chat/mobile-app/testing-your-mobile-app#code-formatting) of the Developer's doc says to run `yarn prettier` in the terminal to fix code formatting issues, but the actual command is `yarn prettier-lint`, as can be seen in the `package.json` file of the [corresponding repo](https://github.com/RocketChat/Rocket.Chat.ReactNative):

https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/4dfc9c70f3ccd00016edf9c11701fda2b3b5f162/package.json#L1-L10

I'm happy to open a PR to fix this once I have confirmation.

**Comment by Rodriq** [comment]
Good one.

**Comment by Faria-TechWrite** [comment]
Resolved
