### ISSUE TITLE
Contribution Guidelines Link is Broken - dev docs

### ISSUE THREAD

**Issue by dhruvtrip** [RocketChat/developer-docs#169]
## Topic - Rocket Chat developer docs

I was trying to access the Contribution Guidelines link from the developer documentation of your open source project but unfortunately, the link seems to be broken. 

Tested on: Safari & Brave browsers on Mac

Link: https://developer.rocket.chat/ 

<img width="852" alt="issue-rocket-chat-dev-docs" src="https://user-images.githubusercontent.com/16800201/233472611-fd29b751-2fde-4e5c-92da-e4c6d7ca13b5.png">

**Comment by Faria-TechWrite** [comment]
Fixed
