### ISSUE TITLE
Url incorret API

### ISSUE THREAD

**Issue by jhuliocastro** [RocketChat/developer-docs#173]
Hi, I believe the callback URL in the [Productivity Totalizers](https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/omnichannel-endpoints/dashboards/productivity-totalizers) section is incorrect. The correct one should be /api/v1/livechat/analytics/dashboards/productivity-totalizers.

**Comment by Faria1212** [comment]
Corrected. We appreciate your input.
