### ISSUE TITLE
Getting "page not found error on URL : https://developer.rocket.chat/rocket.chat/contribute-to-rocket.chat"

### ISSUE THREAD

**Issue by gopalmani** [RocketChat/developer-docs#179]
-->

### Description:
Getting "page not found error on URL : https://developer.rocket.chat/rocket.chat/contribute-to-rocket.chat"

### Steps to reproduce:

1. Go to : https://developer.rocket.chat/contribute-to-rocket.chat/ways-to-contribute/developing
2. Click on : 

<img width="1680" alt="Screenshot 2023-07-04 at 5 01 58 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/45264570/122ceef3-2155-46de-836e-9090d3788a30">

3. Getting Page not found error as per ss below : 

<img width="1678" alt="Screenshot 2023-07-04 at 5 01 19 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/45264570/0d720871-5651-4736-be1d-758e6ee93c29">

**Comment by Faria1212** [comment]
Thanks for raising this. The link became redundant after the new navigation. We removed it.
