### ISSUE TITLE
Missing "install" keyword in command to install required tools

### ISSUE THREAD

**Issue by aradhya-gupta** [RocketChat/developer-docs#18]
Under the "Developing in Windows 10"  section of the Developer Guides, the command to install required tools is incomplete and does not work due to the missing "install" keyword.
It should be "sudo apt-get **install** build-essential git curl python-minimal" instead of "sudo apt-get build-essential git curl python-minimal"

**Comment by Rodriq** [comment]
Closing this issue since this has been addressed [Here](https://developer.rocket.chat/quick-start/choosing-a-development-host/windows-10#setting-up-development-environment)
