### ISSUE TITLE
Possible error in OAuth2 documentation

### ISSUE THREAD

**Issue by Rinps** [RocketChat/developer-docs#183]
First off, this is my first issue on Github, I apologize if this shouldn't be reported here or the issue is missing information.

While developping a Rocket application for my company, I ran into trouble while trying to figure out how OAuth2 works.

When I try to implement the first 2 code snippets from https://developer.rocket.chat/apps-engine/building-custom-apps/adding-features/oauth2-client, which give the following myApp.ts: 

```
import {
	IAppAccessors,
	ILogger,
	IConfigurationExtend,
} from '@rocket.chat/apps-engine/definition/accessors';
import { ApiSecurity, ApiVisibility } from '@rocket.chat/apps-engine/definition/api';
import { App } from '@rocket.chat/apps-engine/definition/App';
import { IAppInfo, RocketChatAssociationModel } from '@rocket.chat/apps-engine/definition/metadata';
import { IAuthData } from '@rocket.chat/apps-engine/definition/oauth2/IOAuth2';
import { createOAuth2Client } from '@rocket.chat/apps-engine/definition/oauth2/OAuth2';

import myEndpoint from './endpoints/myEndpoint';

export class myApp extends App {
	constructor(info: IAppInfo, logger: ILogger, accessors: IAppAccessors) {
		super(info, logger, accessors);
	}

	protected async extendConfiguration(configuration: IConfigurationExtend): Promise<void> {
		// Add the endpoints
		configuration.api.provideApi({
			visibility: ApiVisibility.PUBLIC,
			security: ApiSecurity.UNSECURE,
			endpoints: [new myEndpoint(this)]
		})

		try {
            await createOAuth2Client(this, this.config)
                .setup(configuration);
            await configuration.slashCommands.provideSlashCommand(new AuthCommandCommand(this));
        } catch (error) {
            this.getLogger().error('[extendConfiguration] error', error);
        }
	}
}
```

The line `await createOAuth2Client(this, this.config)` display an error in my IDE (I'm using VSCode) : `Property 'config' does not exist on type 'RocklabApp. ts(2339)`

The line `await configuration.slashCommands.provideSlashCommand(new AuthCommandCommand(this))` also display an error : `Cannot find name 'AuthCommandCommand'. ts(2304)`

The second error makes me think that the code snippets are missing an import or a definition for AuthCommandCommand, or that this line may be an error.

Also, the first line of **Using OAuth2** paragraph doesn't seem to be finished, is this another error ?

**Comment by Rodriq** [comment]
@Rinps The docs have been updated. Please I'll suggest you read and see how to adapt the code for your use case and not necessarily copy-paste the exact code snippets.

Thank you.
