### ISSUE TITLE
Missing information in endpoint

### ISSUE THREAD

**Issue by jhuliocastro** [RocketChat/developer-docs#188]
In [Load History](https://developer.rocket.chat/reference/api/realtime-api/method-calls/rooms/load-history), the following informations is missing

- The endpoint for query is missing
- The "id" parameter, there is no explanation of where the value comes from
- In Example Call, is informed that the content is as json, but in fact, it only works by sending it as a string

![Captura de tela de 2023-08-23 09-29-52](https://github.com/RocketChat/developer-docs/assets/50423683/d305f774-95f9-45c3-b59b-4a9f09ef4898)

**Comment by iagocarmona** [comment]
Hello, can I try to resolve this issue ?
