### ISSUE TITLE
*Feature Request * - REST API - Return User "Last Login/active"

### ISSUE THREAD

**Issue by mariusiscoding** [RocketChat/developer-docs#2]
It would be nice to get a timestamp from the API where I can see the last activity status of a user.

Can you implement this?

I clicked through all endpoints in the doc or did I miss something and this information is already provided?

**Comment by Rodriq** [comment]
If you go through the response from the `users.info` endpoint when called by an admin user, there is a `lastLogin` property.
See documentation here https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/users-endpoints/get-users-info
