### ISSUE TITLE
[Accessibility] : Dark Mode Theme

### ISSUE THREAD

**Issue by Akshun-01** [RocketChat/developer-docs#200]
Hey, I was just going through the docs and couldn't find the dark them button. (idk if I missed it)
But I think that having dark theme is really important specially for a documentation website, as it is far less stressful for the eyes. 
I can use external extensions, but I think that this accessibility feature can directly be added to the site!

**Comment by Akshun-01** [comment]
If you think, we need to integrate this feature, I would love to help in the contribution! ^^

**Comment by Faria1212** [comment]
Fixed!
