### ISSUE TITLE
Missing information for "stream-room-messages"

### ISSUE THREAD

**Issue by mhutter** [RocketChat/developer-docs#201]
1. `__my_messages__` magic `roomId` not documented
2. "back-compatibility" not documented

Only by accident, while reading the JS SDK's source code, I found out that there is the `__my_messages__` magic parameter one can use as the `roomId` in [stream-room-messages](https://developer.rocket.chat/reference/api/realtime-api/subscriptions/streamlivechatroom) to get a stream of all messages in rooms the user _would_ have access to. (weird design choice to have "MY messages" contain messages of rooms I have not joined, but that's besides the point).

Additionally the description of the second parameters says

> Boolean to set back-compatibility.

but does not explain what "back-compatibility" actually means.

**Comment by rachana-visavadiya** [comment]
1. The `__my_messages__` parameter is not used by the Rocket.Chat client, it is only used by the bot SDK. whenever a message is sent to that stream with a room ID, it is also sent to the `__my_messages__` ID. If a client subscribes to it, they will get notified of every message that they have access to. We do not recommend subscribing to it for standard use cases, it's only really useful for bots that need to read every single message.
2. The `back-compatibility` parameter is now mentioned with the explanation on the [Subscriptions](https://developer.rocket.chat/reference/api/realtime-api/subscriptions) page.
Thank you!
