### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by demesg** [RocketChat/developer-docs#202]
in RC 6.5.2 Console log tells me: 
"DeprecationWarning","section":"API","msg":"The parameter "fields" in the endpoint "/api/v1/users.list" is deprecated and will be removed on version 7.0.0"}"

This was a suprise for me. 
Please update the documentation and be very clear with bold letters if this is true.

**Comment by rachana-visavadiya** [comment]
Hi! Based on the code base, the `fields` query parameter is planned for deprecation from the 7.0.0 release version. The documentation will be accordingly updated well in advance of the major release with the information about the relevant changes. 

Thank you!
