### ISSUE TITLE
Improve OAUTH Docs

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/developer-docs#32]
https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/5.%20Administrator%20Guides/Authentication/OAuth/README.md

Specifically maybe we should give a bit more walk through on some.  Some people have issues getting the client id and secret, due to naming and other misc reasons.

**Comment by Faria-TechWrite** [comment]
New documentation is out for OAuth.. https://docs.rocket.chat/guides/administration/settings/oauth we are going to add more shortly.
