### ISSUE TITLE
How to deploy customized version of RC?

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/developer-docs#33]
As described in [this](https://github.com/RocketChat/Rocket.Chat/issues/6525) we are missing docs for creating a custom docker image.  I done some changes on my RC and every time I deploy it with [pm2-meteor](https://github.com/andruschka/pm2-meteor) with single instance mongo but I want use docker and replicaset. I can't find any docs about **how to deploy customized version of RC**. It's all about snap install or completely manual install. Can you help me about it?

**Comment by Rodriq** [comment]
Following all the conversations, we now have a section in the dev docs that talks a little about this. https://developer.rocket.chat/rocket.chat/white-labelling-rocket.chat/customizing-rocket.chat-from-code
