### ISSUE TITLE
update documentation for uploading file using ufsCreate  

### ISSUE THREAD

**Issue by AnshD12** [RocketChat/developer-docs#36]
Please update the documentation for sendMessage method for file upload.
since slingshot has been deprecated please update how to call httprequest for the URL which we get after ufsCreate method outside meteor project.

**Comment by Rodriq** [comment]
Upload file endpoint here https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/rooms-endpoints/upload-file-to-a-room
