### ISSUE TITLE
stream room messages not working

### ISSUE THREAD

**Issue by ashokj82** [RocketChat/developer-docs#50]
I followed https://github.com/RocketChat/docs/tree/master/developer-guides/realtime-api/livechat-api. I have registered a guest user and agent is getting a message. But when I subscribe for stream-room-messages, its not working. When I refer subscription docs it says you need to login but in case of guest user we dont have any login procedure. Please help me how can I subscribe guest user messages.

**Comment by ChristySujitha** [comment]
Updated the documentation. Please refer to this link : https://developer.rocket.chat/reference/api/realtime-api/subscriptions/stream-room-messages.
