### ISSUE TITLE
wording error in link https://rocket.chat/docs/developer-guides/ui-and-theming/themes/ 

### ISSUE THREAD

**Issue by mamashuodedui** [RocketChat/developer-docs#52]
### Description:

in https://rocket.chat/docs/developer-guides/ui-and-theming/themes/, there is no rocketchat-theme in the code repo but rocketchat_theme which will confuse contributor

### Steps to reproduce:

1. open https://rocket.chat/docs/developer-guides/ui-and-theming/themes
2. rocketchat-theme should be "rocketchat_theme"

### Expected behavior:

rocketchat-theme should be "rocketchat_theme"

### Server Setup Information:

**Comment by Rodriq** [comment]
Permalinks are generally in the format `path/to/article/page-name` 
Docs on theming is now here https://developer.rocket.chat/desktop-app/desktop-app-white-labelling
