### ISSUE TITLE
Link broken in iframe integration docs

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/developer-docs#56]
On https://rocket.chat/docs/developer-guides/iframe-integration/, the using `Using embedded layout mode` is not properly working.

**Comment by Rodriq** [comment]
This doc has been moved. Here is the new location and the guide works well. https://developer.rocket.chat/rocket.chat/embedded-layout
![image](https://user-images.githubusercontent.com/39289592/169801961-8a507456-317e-4675-90ed-0479e1bc4b4f.png)
