### ISSUE TITLE
Readme File is broken

### ISSUE THREAD

**Issue by rahljoshi** [RocketChat/developer-docs#74]
Readme file is broken. All the details, headings, links are not working.
![image](https://user-images.githubusercontent.com/59885237/147422200-187d80ae-5b57-43b3-a2e2-8bda08a5d99d.png)

**Comment by Faria-TechWrite** [comment]
Thank you for your contribution. We will try to fix it asap.

**Comment by Faria-TechWrite** [comment]
Resolved!

**Comment by rahljoshi** [comment]
links are working but again there are issues, like this
![image](https://user-images.githubusercontent.com/59885237/147466218-4cbcc6be-b4ed-45cc-bba0-3544581acec5.png)
the whole readme file is looking like this which is not well defined I guess
![image](https://user-images.githubusercontent.com/59885237/147466162-66644a51-78fa-408e-b2dd-f0b64d83fdd0.png)

**Comment by Faria-TechWrite** [comment]
Fixed!
