### ISSUE TITLE
Invite endpoints missing instructions to invite users in bulk to a room

### ISSUE THREAD

**Issue by murtaza98** [RocketChat/developer-docs#81]
Rest Endpoints like `channel.invite` - [Docs link](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/invite) - is missing a param `userIds` which is an array of `userIds`. This enables adding users in bulk to a room. 
Following are the valid payloads for this endpoint:

`{ "roomId": "ByehQjC44FwMeiLbX", "userId": "nSYqWzZ4GsKTX4dyK" }`
`{ "roomId": "ByehQjC44FwMeiLbX", "userIds": ["nSYqWzZ4GsKTX4dyK", "SYqWzZ4Gsasdfgh"] }`

As you can see, either `userIds` or userId param is required

PS: similar change is required for `groups.invite` endpoint docs - [docs link](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/groups-endpoints/invite)

**Comment by Faria-TechWrite** [comment]
Done. Please verify!

**Comment by murtaza98** [comment]
Looks good to me @Faria-TechWrite Thanks!!
