### ISSUE TITLE
Missing details related to HelloWorldApp.ts file:

### ISSUE THREAD

**Issue by Rohan749** [RocketChat/developer-docs#91]
In Rocket.chat Devs website -> Creating Your First App -> Registering Slash Command, it should be mentioned in the paragraph that the code provided is for the HelloWorldApp.ts file. 
Please have a look: 
![Screenshot from 2022-03-16 10-36-07](https://user-images.githubusercontent.com/90546860/158520476-14639eb4-655c-4835-9b44-63e613647a5f.png)

**Comment by debdutdeb** [comment]
I'm confused 🤔 it looks to be mentioned there

**Comment by Rohan749** [comment]
I'm closing this issue. I understood where I was not getting the concept. Thanks!
