### ISSUE TITLE
Error Response while Handelling Interaction Button in parameter of openModalViewResponse().

### ISSUE THREAD

**Issue by Rohan749** [RocketChat/developer-docs#96]
<h2>Description: </h2>
<p>While learning about UI Kit, I registered a button following the steps which ended up perfectly. 
For "handling the interaction", I followed the code which was given on the dev's website. I tried multiple times but it always comes up with this error in the parameter of openModalViewResponse(): </p>

![Screenshot from 2022-03-20 12-18-40](https://user-images.githubusercontent.com/90546860/159626619-a174cfa3-d62e-49a7-a2e6-b7b44518bc9d.png)

<h3>Steps to Reproduce:</h3>
<ol>
<li> Go to Rocket.chat Devs -> Apps Engine -> Adding Features -> UI Kit -> Action Buttons</li>
<li> Under Handling the Interaction, the code is provided. If the code is used in a local machine, it shows a problem in "Blocks".</li>
</ol>
<div><strong>Link To the page Source:</strong>

  https://developer.rocket.chat/apps-engine/fundamentals-of-apps/uikit/action-buttons

</div>

<nav>Please suggest a solution to this problem. </nav>

**Comment by Rodriq** [comment]
@Rohan749 What version of Apps Engine are you using?

**Comment by Rodriq** [comment]
The docs we're missing a call to this method https://rocketchat.github.io/Rocket.Chat.Apps-engine/classes/uikit_blocks_blockbuilder.blockbuilder.html#getblocks

This is the one that actually returns the array of blocks ( length, pop, push, concat, etc are methods in JS Array), but currently the property is being assigned an instance of BlockBuilder

The docs will be updated.
